/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.6/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.jvm)

    // Apply the java-library plugin for API and implementation separation.
    `java-library`

    `maven-publish`
    signing
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    withJavadocJar()
    withSourcesJar()
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

val publish = project.hasProperty("ossrh_user")
if (!publish) {
    println("=== Publish skipped because no credential is provided. ===")
}
val user:String = project.properties["ossrh_user"].toString()
val pwd:String = project.properties["ossrh_pwd"].toString()

publishing {
    if (publish) {
        publications {
            create<MavenPublication>("ardwloop-ext") {
                from(components["java"])

                groupId = "io.github.llschall"
                artifactId = "ardwloop-ext"
                version = "0.1.1-SNAPSHOT"

                pom {
                    signing {
                        sign("publishing.publications.ardwloop-ext")
                        sign("configurations.archives")
                    }
                    name = "ardwloop-ext"
                    description =
                        "An extended version of ardwloop, with Bluetooth support for Android."
                    url = "https://github.com/llschall/ardwloop-ext"
                    licenses {
                        license {
                            name = "The Apache License, Version 2.0"
                            url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
                        }
                    }
                    developers {
                        developer {
                            id = "llschall"
                            name = "Laurent Schall"
                            email = "llschall@gmx.com"
                        }
                    }
                    scm {
                        url = "https://github.com/llschall/ardwloop-ext.git"
                    }
                }
            }
        }
        repositories {
            maven {
                credentials {
                    username = user
                    password = pwd
                }
                url = uri("https://s01.oss.sonatype.org/content/repositories/snapshots")
            }
        }
    }
}

