/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example

import org.llschall.ardwloop.ArdwloopStarter
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = Library()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }

    @Test
    fun checkArdwloopVersion() {
        assertEquals("0.1.2", ArdwloopStarter.ARDWLOOP_VERSION)
    }


}
